version: '3'

services:
  # Node service
  nest_server:
    container_name: nest_server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
        - NODE_ENV=${NODE_ENV}
        - DB_DIALECT=${DB_DIALECT}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_NAME=${DB_NAME}
    restart: always
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - DB_DIALECT=${DB_DIALECT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/usr/app
      - ./node_modules:/usr/app/node_modules
    # ports:
    #   - ${PORT}:${PORT}
    # expose:
    #   - ${PORT}
    networks:
      - gigs_network
    depends_on:
      - db
    command: yarn start:dev

  # Postgres service
  db:
    container_name: 'gigs_database'
    image: postgres:11.5-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gigs_network

  # Pgadmin service
  pgadmin:
    container_name: 'gigs_pgadmin'
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - './pgadmin:/var/lib/pgadmin'
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - db
    networks:
      - gigs_network

  # Nginx service
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - ${WEBSERVER_PORT}:80
    volumes:
      - ./web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
    depends_on:
      - nest_server
    networks:
      - gigs_network

  # Certbot service
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot-etc:/etc/letsencrypt
  #     - ./certbot-var:/var/lib/letsencrypt
  #     - ./web-root:/var/www/html
  #   depends_on:
  #     - webserver
  #   command: certonly --webroot --webroot-path=/var/www/html --email mohiuddinmostafakamal@gmail.com --agree-tos --no-eff-email --staging -d example.com  -d www.example.com

networks:
  gigs_network:
    driver: bridge
